#!/bin/bash

## cel-convert will conver any running (manjaro atm) machine to one that runs xfce
## with kwin and cairo dock using some fancy configs. This is done by downloading
## all programs required to have a nice working setup with the package manager.
## This comes by default with base, base-devel and git. It does not modify currently
## installed versions of what you had installed before. It will only Download and not
## perform removals at this time.
## This changes some desktop files so they will work with this spin, This means it may
## break functionality while running each of the seperate desktop environments.
## current functionality is irreversible.

## will only break the home drive if anything, you can always replace from /etc/skel since I
## leave that area clean. It will still break the menu. May add an add/remove feature that
## backs up the old stuff for if the user did not like it.

## this is not completed code. Use at your own risk. This will probably work with manjaro :)

pacman -S base base-devel git xfce kdebase-workspace cairo-dock cairo-dock-plugins

rm -rf /tmp/git
mkdir -p /tmp/git
cd /tmp/git
git clone https://github.com/edge226/configs.git
cd configs
git branch desktop
git checkout desktop
git pull origin desktop
cd celme
chown -R root:root usr
rsync -rqplH usr /
rsync -rqplH etc/skel/ ~/
rm -rf /tmp/git
